<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="FB_Test" Id="{83ee7ad1-7e96-4758-ada7-f2e2ba9c1f26}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Test
VAR_INPUT
T	:BOOL;;
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[T	:=TRUE;]]></ST>
    </Implementation>
    <LineIds Name="FB_Test">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>